// Generated by CoffeeScript 1.10.0
var URL, server, should, supertest;

supertest = require('supertest');

URL = 'http://localhost:3000/graphql';

server = supertest.agent(URL);

should = require('should');

describe('Unit Test :: Access Home Page', function() {
  it('should test server is up and running', function(done) {
    return server.post('/').set('Content-Type', 'application/graphql').expect(200, done);
  });
  it('should get __schema', function(done) {
    var expectedResult;
    expectedResult = {
      "data": {
        "__schema": {
          "queryType": {
            "name": "RootQueryType",
            "fields": [
              {
                "name": "count",
                "description": "The count!"
              }
            ]
          }
        }
      }
    };
    return server.post('/').type('form').set('Content-Type', 'application/graphql').send('{__schema { queryType { name, fields { name, description} }}}').end(function(err, res) {
      JSON.parse(res.text).should.eql(expectedResult);
      return done();
    });
  });
  it('should get { count }', function(done) {
    var expectedResult;
    expectedResult = {
      data: {
        count: 0
      }
    };
    return server.post('/').type('form').set('Content-Type', 'application/graphql').send('{ count }').end(function(err, res) {
      res.status.should.equal(200);
      JSON.parse(res.text).should.eql(expectedResult);
      return done();
    });
  });
  it('should mutate { count }', function(done) {
    var expectedResult;
    expectedResult = {
      data: {
        updateCount: 1
      }
    };
    return server.post('/').type('form').set('Content-Type', 'application/graphql').send('mutation RootMutationType { updateCount }').end(function(err, res) {
      JSON.parse(res.text).should.eql(expectedResult);
      return done();
    });
  });
  it('should mutate { count } again', function(done) {
    var expectedResult;
    expectedResult = {
      data: {
        updateCount: 2
      }
    };
    return server.post('/').type('form').set('Content-Type', 'application/graphql').send('mutation RootMutationType { updateCount }').end(function(err, res) {
      JSON.parse(res.text).should.eql(expectedResult);
      return done();
    });
  });
  return it('should get updated { count }', function(done) {
    var expectedResult;
    expectedResult = {
      data: {
        count: 2
      }
    };
    return server.post('/').type('form').set('Content-Type', 'application/graphql').send('{ count }').end(function(err, res) {
      res.status.should.equal(200);
      JSON.parse(res.text).should.eql(expectedResult);
      return done();
    });
  });
});
